export const rulesQualityOverrideTranslations = {
  en: {},
  es: {},
  fil: {
    rulesText: `<b>Bago magmungkahi ng nobela</b>\n\nIbigay ang raw/original file, pangunahing mga genre at tag, lahat ng fetish, kink, at sexual content, pati anumang matindi, nakakabahala, kontrobersiyal, o sensitibong content. Huwag sadyang itago o hindi banggitin ang mahahalagang tag o fetish content.\n\n<b>Hindi ako tumatanggap ng nobelang may:</b>\n• Guro, extreme gore, mutilation, dismemberment, o graphic body horror\n• Sexual o sexualized content na kinasasangkutan ng menor de edad o underage na character\n• Bestiality / zoophilia\n• Necrophilia\n• Scat / coprophilia / human toilet\n• Snuff\n• Extreme o sexualized torture\n• Cannibalism\n• Vomit / emetophilia fetish content\n• Parasite / infestation fetish content\n• Unbirthing o katulad na extreme fetish content\n• Futanari / futa\n• Babaeng pangunahing tauhan\n• Totoong tao na ginamit bilang character\n• Gender bender (MtF)\n• Iba pang extreme fetish, disturbing, o shock content ayon sa aking pasya\n\n<b>Mga Patakaran sa Translation at Reposting</b>\nHuwag kopyahin, i-repost, i-reupload, i-mirror, o i-publish ang aking mga translation sa ibang website, app, platform, o community nang walang pahintulot. Ayos lang ang pagbabahagi ng link papunta sa orihinal na translation.`,
    rulesGate: 'Basahin ang mga patakaran sa itaas. Sa pagpapatuloy, kinukumpirma mong walang ipinagbabawal na content ang nobela at naibigay mo nang tapat ang mahahalagang tag, fetish/sexual content, at sensitibong content.',
  },
  hi: {
    rulesText: `<b>उपन्यास भेजने से पहले</b>\n\nमूल/raw फ़ाइल, मुख्य शैलियाँ और टैग, सभी फेटिश, किंक और यौन सामग्री, तथा किसी भी अत्यधिक, परेशान करने वाली, विवादास्पद या संवेदनशील सामग्री की जानकारी दें। महत्वपूर्ण टैग या फेटिश सामग्री जानबूझकर न छिपाएँ।\n\n<b>मैं ऐसे उपन्यास स्वीकार नहीं करता जिनमें:</b>\n• Guro, extreme gore, mutilation, dismemberment या graphic body horror\n• नाबालिग या underage पात्रों से जुड़ी यौन या sexualized सामग्री\n• Bestiality / zoophilia\n• Necrophilia\n• Scat / coprophilia / human toilet\n• Snuff\n• Extreme या sexualized torture\n• Cannibalism\n• Vomit / emetophilia fetish content\n• Parasite / infestation fetish content\n• Unbirthing या इसी तरह की extreme fetish सामग्री\n• Futanari / futa\n• महिला मुख्य पात्र\n• वास्तविक लोगों को पात्रों के रूप में इस्तेमाल करना\n• Gender bender (MtF)\n• मेरे विवेक से अन्य extreme fetish, disturbing या shock content\n\n<b>अनुवाद और पुनर्प्रकाशन के नियम</b>\nमेरी अनुमति के बिना मेरे अनुवाद को किसी अन्य वेबसाइट, ऐप, प्लेटफ़ॉर्म या समुदाय पर कॉपी, repost, reupload, mirror या प्रकाशित न करें। मूल अनुवाद का लिंक साझा करना पूरी तरह ठीक है।`,
    rulesGate: 'ऊपर के नियम पढ़ें। आगे बढ़कर आप पुष्टि करते हैं कि उपन्यास में प्रतिबंधित सामग्री नहीं है और आपने महत्वपूर्ण टैग, फेटिश/यौन सामग्री तथा संवेदनशील सामग्री ईमानदारी से बताई है।',
  },
  pt: {},
  id: {},
  vi: {
    rulesText: `<b>Trước khi đề xuất tiểu thuyết</b>\n\nHãy cung cấp file raw/original, các thể loại và tag chính, toàn bộ fetish, kink và nội dung tình dục, cùng mọi nội dung cực đoan, gây khó chịu, gây tranh cãi hoặc nhạy cảm. Không cố ý che giấu hay bỏ sót tag hoặc fetish content quan trọng.\n\n<b>Tôi không nhận tiểu thuyết có:</b>\n• Guro, gore cực đoan, mutilation, dismemberment hoặc graphic body horror\n• Nội dung tình dục hoặc tình dục hóa liên quan đến người chưa thành niên\n• Bestiality / zoophilia\n• Necrophilia\n• Scat / coprophilia / human toilet\n• Snuff\n• Tra tấn cực đoan hoặc mang tính tình dục\n• Cannibalism\n• Fetish nôn mửa / emetophilia\n• Fetish ký sinh trùng / infestation\n• Unbirthing hoặc fetish cực đoan tương tự\n• Futanari / futa\n• Nhân vật chính là nữ\n• Người thật được dùng làm nhân vật\n• Gender bender (MtF)\n• Nội dung fetish cực đoan, gây khó chịu hoặc gây sốc khác theo quyết định của tôi\n\n<b>Quy định về bản dịch và đăng lại</b>\nKhông sao chép, đăng lại, tải lại, mirror hoặc xuất bản bản dịch của tôi trên website, ứng dụng, nền tảng hay cộng đồng khác khi chưa được phép. Bạn hoàn toàn có thể chia sẻ liên kết đến bản dịch gốc.`,
    rulesGate: 'Hãy đọc các quy định ở trên. Khi tiếp tục, bạn xác nhận tiểu thuyết không có nội dung bị cấm và đã khai báo trung thực các tag quan trọng, nội dung fetish/tình dục và nội dung nhạy cảm.',
  },
  fr: {},
  de: {
    rulesText: `<b>Bevor du einen Roman vorschlägst</b>\n\nBitte sende die Raw-/Originaldatei, die wichtigsten Genres und Tags, alle Fetische, Kinks und sexuellen Inhalte sowie alle extremen, verstörenden, kontroversen oder potenziell sensiblen Inhalte. Wichtige Tags oder Fetischinhalte dürfen nicht absichtlich verschwiegen werden.\n\n<b>Ich akzeptiere keine Romane mit:</b>\n• Guro, extremem Gore, Verstümmelung, Zerstückelung oder grafischem Body Horror\n• Sexuellen oder sexualisierten Inhalten mit Minderjährigen oder minderjährigen Figuren\n• Bestiality / Zoophilie\n• Nekrophilie\n• Scat / Koprophilie / human toilet\n• Snuff\n• Extremer oder sexualisierter Folter\n• Kannibalismus\n• Erbrechen-/Emetophilie-Fetischinhalten\n• Parasiten-/Infestations-Fetischinhalten\n• Unbirthing oder ähnlichen extremen Fetischinhalten\n• Futanari / futa\n• Einer weiblichen Hauptfigur\n• Echten Personen als Figuren\n• Gender-bender-(MtF)-Geschichten\n• Anderen extremen Fetisch-, verstörenden oder Schockinhalten nach meinem Ermessen\n\n<b>Regeln für Übersetzungen und Reposts</b>\nMeine Übersetzungen dürfen ohne Erlaubnis nicht kopiert, repostet, erneut hochgeladen, gespiegelt oder auf anderen Websites, Apps, Plattformen oder in Communities veröffentlicht werden. Einen Link zur ursprünglichen Übersetzung zu teilen ist völlig in Ordnung.`,
    rulesGate: 'Bitte lies die Regeln oben. Mit dem Fortfahren bestätigst du, dass der Roman keine verbotenen Inhalte enthält und dass du wichtige Tags, Fetisch-/Sexualinhalte und sensible Inhalte ehrlich angegeben hast.',
  },
  ru: {},
} as const;
