Foreground yes
TCPSocket 3310
TCPAddr 127.0.0.1
User clamav
DatabaseDirectory /var/lib/clamav
StreamMaxLength 128M
MaxFileSize 128M
MaxScanSize 256M
MaxRecursion 32
MaxFiles 10000
ReadTimeout 600
CommandReadTimeout 30
SendBufTimeout 500
LogTime yes
LogClean no
